//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrekMe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrekMe.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string AboutBack {
            get {
                return ResourceManager.GetString("AboutBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt: .
        /// </summary>
        public static string Alt {
            get {
                return ResourceManager.GetString("Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to altitude m.
        /// </summary>
        public static string Altitude2 {
            get {
                return ResourceManager.GetString("Altitude2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettings {
            get {
                return ResourceManager.GetString("AppBarSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrekMe.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average speed:.
        /// </summary>
        public static string AverageSpeed {
            get {
                return ResourceManager.GetString("AverageSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching GPS data, please wait..
        /// </summary>
        public static string BannerInfo {
            get {
                return ResourceManager.GetString("BannerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break:  .
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories:.
        /// </summary>
        public static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current speed:.
        /// </summary>
        public static string CurrentSpeed {
            get {
                return ResourceManager.GetString("CurrentSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed data.
        /// </summary>
        public static string DetailTitle {
            get {
                return ResourceManager.GetString("DetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance:  .
        /// </summary>
        public static string Distance2 {
            get {
                return ResourceManager.GetString("Distance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source app created by Zlatko Babic, 2015.
        /// </summary>
        public static string Info1 {
            get {
                return ResourceManager.GetString("Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://sourceforge.net/projects/trekme/.
        /// </summary>
        public static string Info1_2 {
            get {
                return ResourceManager.GetString("Info1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Info2 {
            get {
                return ResourceManager.GetString("Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo portion of the NExtra class provided by Daniel Saidi..
        /// </summary>
        public static string Info3 {
            get {
                return ResourceManager.GetString("Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warenhouse Standard font is licensed under SIL Open Font License.
        /// </summary>
        public static string Info4 {
            get {
                return ResourceManager.GetString("Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspired by Colin Eberhardt&apos;s sample WP8Runner.
        /// </summary>
        public static string Info5 {
            get {
                return ResourceManager.GetString("Info5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latitude.
        /// </summary>
        public static string Latitude2 {
            get {
                return ResourceManager.GetString("Latitude2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longitude.
        /// </summary>
        public static string Longitude2 {
            get {
                return ResourceManager.GetString("Longitude2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseButton {
            get {
                return ResourceManager.GetString("PauseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string SettingsBack {
            get {
                return ResourceManager.GetString("SettingsBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map pitch.
        /// </summary>
        public static string SettingsMapTilt {
            get {
                return ResourceManager.GetString("SettingsMapTilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        public static string SpeedMap {
            get {
                return ResourceManager.GetString("SpeedMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopButton {
            get {
                return ResourceManager.GetString("StopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- swipe to return to app --.
        /// </summary>
        public static string SwipeBack {
            get {
                return ResourceManager.GetString("SwipeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- swipe left or right to see the map --.
        /// </summary>
        public static string SwipeText {
            get {
                return ResourceManager.GetString("SwipeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: .
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string Time2 {
            get {
                return ResourceManager.GetString("Time2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance: 0 Speed: 0.
        /// </summary>
        public static string WideContent1 {
            get {
                return ResourceManager.GetString("WideContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. speed: 0 Time: 00:00:00.
        /// </summary>
        public static string WideContent2 {
            get {
                return ResourceManager.GetString("WideContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude Latitude Altitude.
        /// </summary>
        public static string WideContent3 {
            get {
                return ResourceManager.GetString("WideContent3", resourceCulture);
            }
        }
    }
}
